<?php
/**
 * InlineResponse2001List
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  com.lodgea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lodgea-php
 *
 * LODGEA SDK for php. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com.lodgea\com.lodgea.model;

use \ArrayAccess;
use \com.lodgea\ObjectSerializer;

/**
 * InlineResponse2001List Class Doc Comment
 *
 * @category Class
 * @package  com.lodgea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class InlineResponse2001List implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_1_list';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'code' => 'string',
        'language_code' => 'string',
        'currency_code' => 'string',
        'unit_system' => 'string',
        'name' => 'string',
        'uri' => 'string',
        'service_list' => 'float[]',
        'category_list' => 'float[]',
        'uri_path' => 'string',
        'text' => 'string',
        'geo' => '\com.lodgea\com.lodgea.model\InlineResponse2001Geo',
        'media_list' => '\com.lodgea\com.lodgea.model\InlineResponse2001MediaList[]',
        'attraction_list' => '\com.lodgea\com.lodgea.model\InlineResponse2001AttractionList[]',
        'lowest_price' => '\com.lodgea\com.lodgea.model\InlineResponse2001LowestPrice'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'code' => null,
        'language_code' => null,
        'currency_code' => null,
        'unit_system' => null,
        'name' => null,
        'uri' => null,
        'service_list' => null,
        'category_list' => null,
        'uri_path' => null,
        'text' => null,
        'geo' => null,
        'media_list' => null,
        'attraction_list' => null,
        'lowest_price' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'language_code' => 'languageCode',
        'currency_code' => 'currencyCode',
        'unit_system' => 'unitSystem',
        'name' => 'name',
        'uri' => 'uri',
        'service_list' => 'serviceList',
        'category_list' => 'categoryList',
        'uri_path' => 'uriPath',
        'text' => 'text',
        'geo' => 'geo',
        'media_list' => 'mediaList',
        'attraction_list' => 'attractionList',
        'lowest_price' => 'lowestPrice'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'language_code' => 'setLanguageCode',
        'currency_code' => 'setCurrencyCode',
        'unit_system' => 'setUnitSystem',
        'name' => 'setName',
        'uri' => 'setUri',
        'service_list' => 'setServiceList',
        'category_list' => 'setCategoryList',
        'uri_path' => 'setUriPath',
        'text' => 'setText',
        'geo' => 'setGeo',
        'media_list' => 'setMediaList',
        'attraction_list' => 'setAttractionList',
        'lowest_price' => 'setLowestPrice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'language_code' => 'getLanguageCode',
        'currency_code' => 'getCurrencyCode',
        'unit_system' => 'getUnitSystem',
        'name' => 'getName',
        'uri' => 'getUri',
        'service_list' => 'getServiceList',
        'category_list' => 'getCategoryList',
        'uri_path' => 'getUriPath',
        'text' => 'getText',
        'geo' => 'getGeo',
        'media_list' => 'getMediaList',
        'attraction_list' => 'getAttractionList',
        'lowest_price' => 'getLowestPrice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const UNIT_SYSTEM_METRIC = 'metric';
    const UNIT_SYSTEM_IMPERIAL = 'imperial';
    const SERVICE_LIST_1 = 1;
    const SERVICE_LIST_2 = 2;
    const SERVICE_LIST_3 = 3;
    const SERVICE_LIST_4 = 4;
    const SERVICE_LIST_5 = 5;
    const SERVICE_LIST_6 = 6;
    const SERVICE_LIST_7 = 7;
    const SERVICE_LIST_8 = 8;
    const SERVICE_LIST_9 = 9;
    const SERVICE_LIST_10 = 10;
    const SERVICE_LIST_11 = 11;
    const SERVICE_LIST_12 = 12;
    const SERVICE_LIST_13 = 13;
    const SERVICE_LIST_14 = 14;
    const SERVICE_LIST_15 = 15;
    const SERVICE_LIST_16 = 16;
    const SERVICE_LIST_17 = 17;
    const SERVICE_LIST_18 = 18;
    const SERVICE_LIST_19 = 19;
    const SERVICE_LIST_20 = 20;
    const SERVICE_LIST_21 = 21;
    const SERVICE_LIST_22 = 22;
    const SERVICE_LIST_23 = 23;
    const SERVICE_LIST_24 = 24;
    const SERVICE_LIST_25 = 25;
    const SERVICE_LIST_26 = 26;
    const SERVICE_LIST_27 = 27;
    const SERVICE_LIST_28 = 28;
    const SERVICE_LIST_29 = 29;
    const SERVICE_LIST_30 = 30;
    const SERVICE_LIST_31 = 31;
    const SERVICE_LIST_32 = 32;
    const SERVICE_LIST_33 = 33;
    const SERVICE_LIST_34 = 34;
    const SERVICE_LIST_35 = 35;
    const SERVICE_LIST_36 = 36;
    const SERVICE_LIST_37 = 37;
    const SERVICE_LIST_38 = 38;
    const SERVICE_LIST_39 = 39;
    const SERVICE_LIST_40 = 40;
    const SERVICE_LIST_41 = 41;
    const SERVICE_LIST_42 = 42;
    const SERVICE_LIST_43 = 43;
    const SERVICE_LIST_44 = 44;
    const SERVICE_LIST_45 = 45;
    const SERVICE_LIST_46 = 46;
    const SERVICE_LIST_47 = 47;
    const SERVICE_LIST_48 = 48;
    const SERVICE_LIST_49 = 49;
    const SERVICE_LIST_50 = 50;
    const SERVICE_LIST_51 = 51;
    const SERVICE_LIST_52 = 52;
    const SERVICE_LIST_53 = 53;
    const SERVICE_LIST_54 = 54;
    const SERVICE_LIST_55 = 55;
    const SERVICE_LIST_56 = 56;
    const SERVICE_LIST_57 = 57;
    const SERVICE_LIST_58 = 58;
    const SERVICE_LIST_59 = 59;
    const SERVICE_LIST_60 = 60;
    const SERVICE_LIST_61 = 61;
    const SERVICE_LIST_62 = 62;
    const SERVICE_LIST_63 = 63;
    const SERVICE_LIST_64 = 64;
    const SERVICE_LIST_65 = 65;
    const SERVICE_LIST_66 = 66;
    const SERVICE_LIST_67 = 67;
    const SERVICE_LIST_68 = 68;
    const SERVICE_LIST_69 = 69;
    const SERVICE_LIST_70 = 70;
    const SERVICE_LIST_71 = 71;
    const SERVICE_LIST_72 = 72;
    const SERVICE_LIST_73 = 73;
    const SERVICE_LIST_74 = 74;
    const SERVICE_LIST_75 = 75;
    const SERVICE_LIST_76 = 76;
    const SERVICE_LIST_77 = 77;
    const SERVICE_LIST_78 = 78;
    const SERVICE_LIST_79 = 79;
    const SERVICE_LIST_80 = 80;
    const SERVICE_LIST_81 = 81;
    const SERVICE_LIST_82 = 82;
    const SERVICE_LIST_83 = 83;
    const SERVICE_LIST_84 = 84;
    const SERVICE_LIST_85 = 85;
    const SERVICE_LIST_86 = 86;
    const SERVICE_LIST_87 = 87;
    const SERVICE_LIST_88 = 88;
    const SERVICE_LIST_89 = 89;
    const SERVICE_LIST_90 = 90;
    const SERVICE_LIST_91 = 91;
    const SERVICE_LIST_92 = 92;
    const SERVICE_LIST_93 = 93;
    const SERVICE_LIST_94 = 94;
    const SERVICE_LIST_95 = 95;
    const SERVICE_LIST_96 = 96;
    const SERVICE_LIST_97 = 97;
    const SERVICE_LIST_98 = 98;
    const SERVICE_LIST_99 = 99;
    const SERVICE_LIST_100 = 100;
    const SERVICE_LIST_101 = 101;
    const SERVICE_LIST_102 = 102;
    const SERVICE_LIST_103 = 103;
    const SERVICE_LIST_104 = 104;
    const SERVICE_LIST_105 = 105;
    const SERVICE_LIST_106 = 106;
    const SERVICE_LIST_107 = 107;
    const SERVICE_LIST_108 = 108;
    const SERVICE_LIST_109 = 109;
    const SERVICE_LIST_110 = 110;
    const SERVICE_LIST_111 = 111;
    const SERVICE_LIST_112 = 112;
    const SERVICE_LIST_113 = 113;
    const SERVICE_LIST_114 = 114;
    const SERVICE_LIST_115 = 115;
    const SERVICE_LIST_116 = 116;
    const SERVICE_LIST_117 = 117;
    const SERVICE_LIST_118 = 118;
    const SERVICE_LIST_119 = 119;
    const SERVICE_LIST_120 = 120;
    const SERVICE_LIST_121 = 121;
    const SERVICE_LIST_122 = 122;
    const SERVICE_LIST_123 = 123;
    const SERVICE_LIST_124 = 124;
    const SERVICE_LIST_125 = 125;
    const SERVICE_LIST_126 = 126;
    const SERVICE_LIST_127 = 127;
    const SERVICE_LIST_128 = 128;
    const SERVICE_LIST_129 = 129;
    const SERVICE_LIST_130 = 130;
    const SERVICE_LIST_131 = 131;
    const SERVICE_LIST_132 = 132;
    const SERVICE_LIST_133 = 133;
    const SERVICE_LIST_134 = 134;
    const SERVICE_LIST_135 = 135;
    const SERVICE_LIST_136 = 136;
    const SERVICE_LIST_137 = 137;
    const SERVICE_LIST_138 = 138;
    const SERVICE_LIST_139 = 139;
    const SERVICE_LIST_140 = 140;
    const SERVICE_LIST_141 = 141;
    const SERVICE_LIST_142 = 142;
    const SERVICE_LIST_143 = 143;
    const SERVICE_LIST_144 = 144;
    const SERVICE_LIST_145 = 145;
    const SERVICE_LIST_146 = 146;
    const SERVICE_LIST_147 = 147;
    const SERVICE_LIST_148 = 148;
    const SERVICE_LIST_149 = 149;
    const SERVICE_LIST_150 = 150;
    const SERVICE_LIST_151 = 151;
    const SERVICE_LIST_152 = 152;
    const SERVICE_LIST_153 = 153;
    const SERVICE_LIST_154 = 154;
    const SERVICE_LIST_155 = 155;
    const SERVICE_LIST_156 = 156;
    const SERVICE_LIST_157 = 157;
    const SERVICE_LIST_158 = 158;
    const SERVICE_LIST_159 = 159;
    const SERVICE_LIST_160 = 160;
    const SERVICE_LIST_161 = 161;
    const SERVICE_LIST_162 = 162;
    const SERVICE_LIST_163 = 163;
    const SERVICE_LIST_164 = 164;
    const SERVICE_LIST_165 = 165;
    const SERVICE_LIST_166 = 166;
    const SERVICE_LIST_167 = 167;
    const SERVICE_LIST_168 = 168;
    const SERVICE_LIST_169 = 169;
    const SERVICE_LIST_170 = 170;
    const SERVICE_LIST_171 = 171;
    const SERVICE_LIST_172 = 172;
    const SERVICE_LIST_173 = 173;
    const SERVICE_LIST_174 = 174;
    const SERVICE_LIST_175 = 175;
    const SERVICE_LIST_176 = 176;
    const SERVICE_LIST_177 = 177;
    const SERVICE_LIST_178 = 178;
    const SERVICE_LIST_179 = 179;
    const SERVICE_LIST_180 = 180;
    const SERVICE_LIST_181 = 181;
    const SERVICE_LIST_182 = 182;
    const SERVICE_LIST_183 = 183;
    const SERVICE_LIST_184 = 184;
    const SERVICE_LIST_185 = 185;
    const SERVICE_LIST_186 = 186;
    const SERVICE_LIST_187 = 187;
    const SERVICE_LIST_188 = 188;
    const SERVICE_LIST_189 = 189;
    const SERVICE_LIST_190 = 190;
    const SERVICE_LIST_191 = 191;
    const SERVICE_LIST_192 = 192;
    const SERVICE_LIST_193 = 193;
    const SERVICE_LIST_194 = 194;
    const SERVICE_LIST_195 = 195;
    const SERVICE_LIST_196 = 196;
    const SERVICE_LIST_197 = 197;
    const SERVICE_LIST_198 = 198;
    const SERVICE_LIST_199 = 199;
    const SERVICE_LIST_200 = 200;
    const SERVICE_LIST_201 = 201;
    const SERVICE_LIST_202 = 202;
    const SERVICE_LIST_203 = 203;
    const SERVICE_LIST_204 = 204;
    const SERVICE_LIST_205 = 205;
    const SERVICE_LIST_206 = 206;
    const SERVICE_LIST_207 = 207;
    const SERVICE_LIST_208 = 208;
    const SERVICE_LIST_209 = 209;
    const SERVICE_LIST_210 = 210;
    const SERVICE_LIST_211 = 211;
    const SERVICE_LIST_212 = 212;
    const SERVICE_LIST_213 = 213;
    const SERVICE_LIST_214 = 214;
    const SERVICE_LIST_215 = 215;
    const SERVICE_LIST_216 = 216;
    const SERVICE_LIST_217 = 217;
    const SERVICE_LIST_218 = 218;
    const SERVICE_LIST_219 = 219;
    const SERVICE_LIST_220 = 220;
    const SERVICE_LIST_221 = 221;
    const SERVICE_LIST_222 = 222;
    const SERVICE_LIST_223 = 223;
    const SERVICE_LIST_224 = 224;
    const SERVICE_LIST_225 = 225;
    const SERVICE_LIST_226 = 226;
    const SERVICE_LIST_227 = 227;
    const SERVICE_LIST_228 = 228;
    const SERVICE_LIST_229 = 229;
    const SERVICE_LIST_230 = 230;
    const SERVICE_LIST_231 = 231;
    const SERVICE_LIST_232 = 232;
    const SERVICE_LIST_233 = 233;
    const SERVICE_LIST_234 = 234;
    const SERVICE_LIST_235 = 235;
    const SERVICE_LIST_236 = 236;
    const SERVICE_LIST_237 = 237;
    const SERVICE_LIST_238 = 238;
    const SERVICE_LIST_239 = 239;
    const SERVICE_LIST_240 = 240;
    const SERVICE_LIST_241 = 241;
    const SERVICE_LIST_242 = 242;
    const SERVICE_LIST_243 = 243;
    const SERVICE_LIST_244 = 244;
    const SERVICE_LIST_245 = 245;
    const SERVICE_LIST_246 = 246;
    const SERVICE_LIST_247 = 247;
    const SERVICE_LIST_248 = 248;
    const SERVICE_LIST_249 = 249;
    const SERVICE_LIST_250 = 250;
    const SERVICE_LIST_251 = 251;
    const SERVICE_LIST_252 = 252;
    const SERVICE_LIST_253 = 253;
    const SERVICE_LIST_254 = 254;
    const SERVICE_LIST_255 = 255;
    const SERVICE_LIST_256 = 256;
    const SERVICE_LIST_257 = 257;
    const SERVICE_LIST_258 = 258;
    const SERVICE_LIST_259 = 259;
    const SERVICE_LIST_260 = 260;
    const SERVICE_LIST_261 = 261;
    const SERVICE_LIST_262 = 262;
    const SERVICE_LIST_263 = 263;
    const SERVICE_LIST_264 = 264;
    const SERVICE_LIST_265 = 265;
    const SERVICE_LIST_266 = 266;
    const SERVICE_LIST_267 = 267;
    const SERVICE_LIST_268 = 268;
    const SERVICE_LIST_269 = 269;
    const SERVICE_LIST_270 = 270;
    const SERVICE_LIST_271 = 271;
    const SERVICE_LIST_272 = 272;
    const SERVICE_LIST_273 = 273;
    const SERVICE_LIST_274 = 274;
    const SERVICE_LIST_275 = 275;
    const SERVICE_LIST_276 = 276;
    const SERVICE_LIST_277 = 277;
    const SERVICE_LIST_278 = 278;
    const SERVICE_LIST_279 = 279;
    const SERVICE_LIST_280 = 280;
    const SERVICE_LIST_281 = 281;
    const SERVICE_LIST_282 = 282;
    const SERVICE_LIST_283 = 283;
    const SERVICE_LIST_284 = 284;
    const SERVICE_LIST_285 = 285;
    const SERVICE_LIST_286 = 286;
    const SERVICE_LIST_287 = 287;
    const SERVICE_LIST_288 = 288;
    const SERVICE_LIST_289 = 289;
    const SERVICE_LIST_290 = 290;
    const SERVICE_LIST_291 = 291;
    const SERVICE_LIST_292 = 292;
    const SERVICE_LIST_293 = 293;
    const SERVICE_LIST_294 = 294;
    const SERVICE_LIST_295 = 295;
    const SERVICE_LIST_296 = 296;
    const SERVICE_LIST_297 = 297;
    const SERVICE_LIST_298 = 298;
    const SERVICE_LIST_299 = 299;
    const SERVICE_LIST_300 = 300;
    const SERVICE_LIST_301 = 301;
    const SERVICE_LIST_302 = 302;
    const SERVICE_LIST_303 = 303;
    const SERVICE_LIST_304 = 304;
    const SERVICE_LIST_305 = 305;
    const SERVICE_LIST_306 = 306;
    const SERVICE_LIST_307 = 307;
    const SERVICE_LIST_308 = 308;
    const SERVICE_LIST_309 = 309;
    const SERVICE_LIST_310 = 310;
    const SERVICE_LIST_311 = 311;
    const SERVICE_LIST_312 = 312;
    const SERVICE_LIST_313 = 313;
    const SERVICE_LIST_314 = 314;
    const SERVICE_LIST_315 = 315;
    const SERVICE_LIST_316 = 316;
    const SERVICE_LIST_317 = 317;
    const SERVICE_LIST_318 = 318;
    const SERVICE_LIST_319 = 319;
    const SERVICE_LIST_320 = 320;
    const SERVICE_LIST_321 = 321;
    const SERVICE_LIST_322 = 322;
    const SERVICE_LIST_323 = 323;
    const SERVICE_LIST_324 = 324;
    const SERVICE_LIST_325 = 325;
    const SERVICE_LIST_326 = 326;
    const SERVICE_LIST_327 = 327;
    const SERVICE_LIST_328 = 328;
    const SERVICE_LIST_329 = 329;
    const SERVICE_LIST_331 = 331;
    const SERVICE_LIST_332 = 332;
    const SERVICE_LIST_333 = 333;
    const SERVICE_LIST_334 = 334;
    const SERVICE_LIST_335 = 335;
    const SERVICE_LIST_336 = 336;
    const SERVICE_LIST_337 = 337;
    const SERVICE_LIST_338 = 338;
    const SERVICE_LIST_339 = 339;
    const SERVICE_LIST_340 = 340;
    const SERVICE_LIST_341 = 341;
    const SERVICE_LIST_342 = 342;
    const SERVICE_LIST_343 = 343;
    const SERVICE_LIST_344 = 344;
    const SERVICE_LIST_345 = 345;
    const SERVICE_LIST_348 = 348;
    const SERVICE_LIST_349 = 349;
    const SERVICE_LIST_350 = 350;
    const SERVICE_LIST_351 = 351;
    const SERVICE_LIST_5000 = 5000;
    const SERVICE_LIST_5001 = 5001;
    const SERVICE_LIST_5002 = 5002;
    const SERVICE_LIST_5003 = 5003;
    const SERVICE_LIST_5004 = 5004;
    const SERVICE_LIST_5005 = 5005;
    const SERVICE_LIST_5006 = 5006;
    const SERVICE_LIST_5007 = 5007;
    const SERVICE_LIST_5008 = 5008;
    const SERVICE_LIST_5009 = 5009;
    const SERVICE_LIST_5010 = 5010;
    const SERVICE_LIST_5011 = 5011;
    const SERVICE_LIST_5012 = 5012;
    const SERVICE_LIST_5013 = 5013;
    const SERVICE_LIST_5014 = 5014;
    const SERVICE_LIST_5015 = 5015;
    const SERVICE_LIST_5016 = 5016;
    const SERVICE_LIST_5017 = 5017;
    const SERVICE_LIST_5018 = 5018;
    const SERVICE_LIST_5020 = 5020;
    const SERVICE_LIST_5021 = 5021;
    const SERVICE_LIST_5022 = 5022;
    const SERVICE_LIST_5023 = 5023;
    const SERVICE_LIST_5024 = 5024;
    const SERVICE_LIST_5025 = 5025;
    const SERVICE_LIST_5026 = 5026;
    const SERVICE_LIST_5027 = 5027;
    const SERVICE_LIST_5028 = 5028;
    const SERVICE_LIST_5029 = 5029;
    const SERVICE_LIST_5030 = 5030;
    const SERVICE_LIST_5031 = 5031;
    const SERVICE_LIST_5032 = 5032;
    const SERVICE_LIST_5033 = 5033;
    const SERVICE_LIST_5034 = 5034;
    const SERVICE_LIST_5035 = 5035;
    const SERVICE_LIST_5036 = 5036;
    const SERVICE_LIST_5037 = 5037;
    const SERVICE_LIST_5039 = 5039;
    const SERVICE_LIST_5040 = 5040;
    const SERVICE_LIST_5041 = 5041;
    const SERVICE_LIST_5042 = 5042;
    const SERVICE_LIST_5043 = 5043;
    const SERVICE_LIST_5044 = 5044;
    const SERVICE_LIST_5045 = 5045;
    const SERVICE_LIST_5046 = 5046;
    const SERVICE_LIST_5047 = 5047;
    const SERVICE_LIST_5048 = 5048;
    const SERVICE_LIST_5049 = 5049;
    const SERVICE_LIST_5050 = 5050;
    const SERVICE_LIST_5051 = 5051;
    const SERVICE_LIST_5052 = 5052;
    const SERVICE_LIST_5053 = 5053;
    const SERVICE_LIST_5054 = 5054;
    const SERVICE_LIST_5055 = 5055;
    const SERVICE_LIST_5056 = 5056;
    const SERVICE_LIST_5057 = 5057;
    const SERVICE_LIST_5058 = 5058;
    const SERVICE_LIST_5059 = 5059;
    const SERVICE_LIST_5060 = 5060;
    const SERVICE_LIST_5061 = 5061;
    const SERVICE_LIST_5062 = 5062;
    const SERVICE_LIST_5063 = 5063;
    const SERVICE_LIST_5064 = 5064;
    const SERVICE_LIST_5065 = 5065;
    const SERVICE_LIST_5066 = 5066;
    const SERVICE_LIST_5067 = 5067;
    const SERVICE_LIST_5068 = 5068;
    const SERVICE_LIST_5069 = 5069;
    const SERVICE_LIST_5070 = 5070;
    const SERVICE_LIST_5071 = 5071;
    const SERVICE_LIST_5072 = 5072;
    const SERVICE_LIST_5073 = 5073;
    const SERVICE_LIST_5074 = 5074;
    const SERVICE_LIST_5075 = 5075;
    const SERVICE_LIST_5076 = 5076;
    const SERVICE_LIST_5077 = 5077;
    const SERVICE_LIST_5078 = 5078;
    const SERVICE_LIST_5079 = 5079;
    const SERVICE_LIST_5080 = 5080;
    const SERVICE_LIST_5081 = 5081;
    const SERVICE_LIST_5082 = 5082;
    const SERVICE_LIST_5083 = 5083;
    const SERVICE_LIST_5084 = 5084;
    const SERVICE_LIST_5085 = 5085;
    const SERVICE_LIST_5086 = 5086;
    const SERVICE_LIST_5087 = 5087;
    const SERVICE_LIST_5088 = 5088;
    const SERVICE_LIST_5089 = 5089;
    const SERVICE_LIST_5090 = 5090;
    const SERVICE_LIST_5091 = 5091;
    const SERVICE_LIST_5092 = 5092;
    const SERVICE_LIST_5093 = 5093;
    const SERVICE_LIST_5094 = 5094;
    const SERVICE_LIST_5095 = 5095;
    const SERVICE_LIST_5096 = 5096;
    const SERVICE_LIST_5097 = 5097;
    const SERVICE_LIST_5098 = 5098;
    const SERVICE_LIST_5099 = 5099;
    const SERVICE_LIST_5100 = 5100;
    const SERVICE_LIST_5101 = 5101;
    const SERVICE_LIST_5102 = 5102;
    const SERVICE_LIST_5103 = 5103;
    const SERVICE_LIST_5104 = 5104;
    const SERVICE_LIST_5105 = 5105;
    const SERVICE_LIST_5106 = 5106;
    const SERVICE_LIST_5107 = 5107;
    const SERVICE_LIST_5108 = 5108;
    const SERVICE_LIST_5109 = 5109;
    const SERVICE_LIST_5110 = 5110;
    const SERVICE_LIST_5111 = 5111;
    const SERVICE_LIST_5112 = 5112;
    const SERVICE_LIST_5113 = 5113;
    const SERVICE_LIST_5114 = 5114;
    const SERVICE_LIST_5115 = 5115;
    const SERVICE_LIST_5116 = 5116;
    const SERVICE_LIST_5117 = 5117;
    const SERVICE_LIST_5118 = 5118;
    const SERVICE_LIST_5119 = 5119;
    const SERVICE_LIST_5120 = 5120;
    const SERVICE_LIST_5121 = 5121;
    const SERVICE_LIST_5122 = 5122;
    const SERVICE_LIST_5123 = 5123;
    const SERVICE_LIST_5124 = 5124;
    const SERVICE_LIST_5125 = 5125;
    const SERVICE_LIST_5126 = 5126;
    const SERVICE_LIST_5127 = 5127;
    const SERVICE_LIST_5128 = 5128;
    const SERVICE_LIST_5129 = 5129;
    const SERVICE_LIST_5130 = 5130;
    const SERVICE_LIST_5131 = 5131;
    const SERVICE_LIST_5132 = 5132;
    const SERVICE_LIST_5133 = 5133;
    const SERVICE_LIST_5134 = 5134;
    const SERVICE_LIST_5135 = 5135;
    const SERVICE_LIST_5136 = 5136;
    const SERVICE_LIST_5137 = 5137;
    const SERVICE_LIST_5138 = 5138;
    const SERVICE_LIST_5139 = 5139;
    const SERVICE_LIST_5140 = 5140;
    const SERVICE_LIST_5141 = 5141;
    const SERVICE_LIST_5142 = 5142;
    const SERVICE_LIST_5143 = 5143;
    const SERVICE_LIST_5144 = 5144;
    const SERVICE_LIST_5145 = 5145;
    const SERVICE_LIST_5146 = 5146;
    const SERVICE_LIST_5147 = 5147;
    const SERVICE_LIST_5148 = 5148;
    const SERVICE_LIST_5149 = 5149;
    const SERVICE_LIST_5150 = 5150;
    const SERVICE_LIST_5151 = 5151;
    const SERVICE_LIST_5152 = 5152;
    const SERVICE_LIST_5153 = 5153;
    const SERVICE_LIST_5154 = 5154;
    const SERVICE_LIST_5156 = 5156;
    const SERVICE_LIST_5157 = 5157;
    const SERVICE_LIST_5158 = 5158;
    const SERVICE_LIST_5159 = 5159;
    const SERVICE_LIST_5160 = 5160;
    const SERVICE_LIST_5161 = 5161;
    const SERVICE_LIST_5162 = 5162;
    const SERVICE_LIST_5163 = 5163;
    const SERVICE_LIST_5164 = 5164;
    const SERVICE_LIST_5165 = 5165;
    const SERVICE_LIST_5166 = 5166;
    const SERVICE_LIST_5167 = 5167;
    const SERVICE_LIST_5168 = 5168;
    const SERVICE_LIST_5169 = 5169;
    const SERVICE_LIST_5170 = 5170;
    const SERVICE_LIST_5171 = 5171;
    const SERVICE_LIST_5172 = 5172;
    const SERVICE_LIST_5173 = 5173;
    const SERVICE_LIST_5174 = 5174;
    const SERVICE_LIST_5175 = 5175;
    const SERVICE_LIST_5176 = 5176;
    const SERVICE_LIST_5177 = 5177;
    const SERVICE_LIST_5178 = 5178;
    const SERVICE_LIST_6000 = 6000;
    const SERVICE_LIST_6001 = 6001;
    const SERVICE_LIST_90001 = 90001;
    const CATEGORY_LIST_1 = 1;
    const CATEGORY_LIST_2 = 2;
    const CATEGORY_LIST_3 = 3;
    const CATEGORY_LIST_4 = 4;
    const CATEGORY_LIST_5 = 5;
    const CATEGORY_LIST_6 = 6;
    const CATEGORY_LIST_7 = 7;
    const CATEGORY_LIST_8 = 8;
    const CATEGORY_LIST_9 = 9;
    const CATEGORY_LIST_10 = 10;
    const CATEGORY_LIST_11 = 11;
    const CATEGORY_LIST_12 = 12;
    const CATEGORY_LIST_13 = 13;
    const CATEGORY_LIST_14 = 14;
    const CATEGORY_LIST_15 = 15;
    const CATEGORY_LIST_16 = 16;
    const CATEGORY_LIST_17 = 17;
    const CATEGORY_LIST_18 = 18;
    const CATEGORY_LIST_19 = 19;
    const CATEGORY_LIST_20 = 20;
    const CATEGORY_LIST_21 = 21;
    const CATEGORY_LIST_22 = 22;
    const CATEGORY_LIST_23 = 23;
    const CATEGORY_LIST_24 = 24;
    const CATEGORY_LIST_25 = 25;
    const CATEGORY_LIST_26 = 26;
    const CATEGORY_LIST_27 = 27;
    const CATEGORY_LIST_28 = 28;
    const CATEGORY_LIST_29 = 29;
    const CATEGORY_LIST_30 = 30;
    const CATEGORY_LIST_31 = 31;
    const CATEGORY_LIST_32 = 32;
    const CATEGORY_LIST_33 = 33;
    const CATEGORY_LIST_34 = 34;
    const CATEGORY_LIST_35 = 35;
    const CATEGORY_LIST_36 = 36;
    const CATEGORY_LIST_37 = 37;
    const CATEGORY_LIST_38 = 38;
    const CATEGORY_LIST_39 = 39;
    const CATEGORY_LIST_40 = 40;
    const CATEGORY_LIST_41 = 41;
    const CATEGORY_LIST_42 = 42;
    const CATEGORY_LIST_43 = 43;
    const CATEGORY_LIST_44 = 44;
    const CATEGORY_LIST_45 = 45;
    const CATEGORY_LIST_46 = 46;
    const CATEGORY_LIST_47 = 47;
    const CATEGORY_LIST_48 = 48;
    const CATEGORY_LIST_49 = 49;
    const CATEGORY_LIST_50 = 50;
    const CATEGORY_LIST_51 = 51;
    const CATEGORY_LIST_52 = 52;
    const CATEGORY_LIST_53 = 53;
    const CATEGORY_LIST_54 = 54;
    const CATEGORY_LIST_55 = 55;
    const CATEGORY_LIST_56 = 56;
    const CATEGORY_LIST_57 = 57;
    const CATEGORY_LIST_58 = 58;
    const CATEGORY_LIST_59 = 59;
    const CATEGORY_LIST_60 = 60;
    const CATEGORY_LIST_61 = 61;
    const CATEGORY_LIST_62 = 62;
    const CATEGORY_LIST_5000 = 5000;
    const CATEGORY_LIST_5001 = 5001;
    const CATEGORY_LIST_5002 = 5002;
    const CATEGORY_LIST_5003 = 5003;
    const CATEGORY_LIST_5004 = 5004;
    const CATEGORY_LIST_5005 = 5005;
    const CATEGORY_LIST_5006 = 5006;
    const CATEGORY_LIST_5007 = 5007;
    const CATEGORY_LIST_5008 = 5008;
    const CATEGORY_LIST_5009 = 5009;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUnitSystemAllowableValues()
    {
        return [
            self::UNIT_SYSTEM_METRIC,
            self::UNIT_SYSTEM_IMPERIAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getServiceListAllowableValues()
    {
        return [
            self::SERVICE_LIST_1,
            self::SERVICE_LIST_2,
            self::SERVICE_LIST_3,
            self::SERVICE_LIST_4,
            self::SERVICE_LIST_5,
            self::SERVICE_LIST_6,
            self::SERVICE_LIST_7,
            self::SERVICE_LIST_8,
            self::SERVICE_LIST_9,
            self::SERVICE_LIST_10,
            self::SERVICE_LIST_11,
            self::SERVICE_LIST_12,
            self::SERVICE_LIST_13,
            self::SERVICE_LIST_14,
            self::SERVICE_LIST_15,
            self::SERVICE_LIST_16,
            self::SERVICE_LIST_17,
            self::SERVICE_LIST_18,
            self::SERVICE_LIST_19,
            self::SERVICE_LIST_20,
            self::SERVICE_LIST_21,
            self::SERVICE_LIST_22,
            self::SERVICE_LIST_23,
            self::SERVICE_LIST_24,
            self::SERVICE_LIST_25,
            self::SERVICE_LIST_26,
            self::SERVICE_LIST_27,
            self::SERVICE_LIST_28,
            self::SERVICE_LIST_29,
            self::SERVICE_LIST_30,
            self::SERVICE_LIST_31,
            self::SERVICE_LIST_32,
            self::SERVICE_LIST_33,
            self::SERVICE_LIST_34,
            self::SERVICE_LIST_35,
            self::SERVICE_LIST_36,
            self::SERVICE_LIST_37,
            self::SERVICE_LIST_38,
            self::SERVICE_LIST_39,
            self::SERVICE_LIST_40,
            self::SERVICE_LIST_41,
            self::SERVICE_LIST_42,
            self::SERVICE_LIST_43,
            self::SERVICE_LIST_44,
            self::SERVICE_LIST_45,
            self::SERVICE_LIST_46,
            self::SERVICE_LIST_47,
            self::SERVICE_LIST_48,
            self::SERVICE_LIST_49,
            self::SERVICE_LIST_50,
            self::SERVICE_LIST_51,
            self::SERVICE_LIST_52,
            self::SERVICE_LIST_53,
            self::SERVICE_LIST_54,
            self::SERVICE_LIST_55,
            self::SERVICE_LIST_56,
            self::SERVICE_LIST_57,
            self::SERVICE_LIST_58,
            self::SERVICE_LIST_59,
            self::SERVICE_LIST_60,
            self::SERVICE_LIST_61,
            self::SERVICE_LIST_62,
            self::SERVICE_LIST_63,
            self::SERVICE_LIST_64,
            self::SERVICE_LIST_65,
            self::SERVICE_LIST_66,
            self::SERVICE_LIST_67,
            self::SERVICE_LIST_68,
            self::SERVICE_LIST_69,
            self::SERVICE_LIST_70,
            self::SERVICE_LIST_71,
            self::SERVICE_LIST_72,
            self::SERVICE_LIST_73,
            self::SERVICE_LIST_74,
            self::SERVICE_LIST_75,
            self::SERVICE_LIST_76,
            self::SERVICE_LIST_77,
            self::SERVICE_LIST_78,
            self::SERVICE_LIST_79,
            self::SERVICE_LIST_80,
            self::SERVICE_LIST_81,
            self::SERVICE_LIST_82,
            self::SERVICE_LIST_83,
            self::SERVICE_LIST_84,
            self::SERVICE_LIST_85,
            self::SERVICE_LIST_86,
            self::SERVICE_LIST_87,
            self::SERVICE_LIST_88,
            self::SERVICE_LIST_89,
            self::SERVICE_LIST_90,
            self::SERVICE_LIST_91,
            self::SERVICE_LIST_92,
            self::SERVICE_LIST_93,
            self::SERVICE_LIST_94,
            self::SERVICE_LIST_95,
            self::SERVICE_LIST_96,
            self::SERVICE_LIST_97,
            self::SERVICE_LIST_98,
            self::SERVICE_LIST_99,
            self::SERVICE_LIST_100,
            self::SERVICE_LIST_101,
            self::SERVICE_LIST_102,
            self::SERVICE_LIST_103,
            self::SERVICE_LIST_104,
            self::SERVICE_LIST_105,
            self::SERVICE_LIST_106,
            self::SERVICE_LIST_107,
            self::SERVICE_LIST_108,
            self::SERVICE_LIST_109,
            self::SERVICE_LIST_110,
            self::SERVICE_LIST_111,
            self::SERVICE_LIST_112,
            self::SERVICE_LIST_113,
            self::SERVICE_LIST_114,
            self::SERVICE_LIST_115,
            self::SERVICE_LIST_116,
            self::SERVICE_LIST_117,
            self::SERVICE_LIST_118,
            self::SERVICE_LIST_119,
            self::SERVICE_LIST_120,
            self::SERVICE_LIST_121,
            self::SERVICE_LIST_122,
            self::SERVICE_LIST_123,
            self::SERVICE_LIST_124,
            self::SERVICE_LIST_125,
            self::SERVICE_LIST_126,
            self::SERVICE_LIST_127,
            self::SERVICE_LIST_128,
            self::SERVICE_LIST_129,
            self::SERVICE_LIST_130,
            self::SERVICE_LIST_131,
            self::SERVICE_LIST_132,
            self::SERVICE_LIST_133,
            self::SERVICE_LIST_134,
            self::SERVICE_LIST_135,
            self::SERVICE_LIST_136,
            self::SERVICE_LIST_137,
            self::SERVICE_LIST_138,
            self::SERVICE_LIST_139,
            self::SERVICE_LIST_140,
            self::SERVICE_LIST_141,
            self::SERVICE_LIST_142,
            self::SERVICE_LIST_143,
            self::SERVICE_LIST_144,
            self::SERVICE_LIST_145,
            self::SERVICE_LIST_146,
            self::SERVICE_LIST_147,
            self::SERVICE_LIST_148,
            self::SERVICE_LIST_149,
            self::SERVICE_LIST_150,
            self::SERVICE_LIST_151,
            self::SERVICE_LIST_152,
            self::SERVICE_LIST_153,
            self::SERVICE_LIST_154,
            self::SERVICE_LIST_155,
            self::SERVICE_LIST_156,
            self::SERVICE_LIST_157,
            self::SERVICE_LIST_158,
            self::SERVICE_LIST_159,
            self::SERVICE_LIST_160,
            self::SERVICE_LIST_161,
            self::SERVICE_LIST_162,
            self::SERVICE_LIST_163,
            self::SERVICE_LIST_164,
            self::SERVICE_LIST_165,
            self::SERVICE_LIST_166,
            self::SERVICE_LIST_167,
            self::SERVICE_LIST_168,
            self::SERVICE_LIST_169,
            self::SERVICE_LIST_170,
            self::SERVICE_LIST_171,
            self::SERVICE_LIST_172,
            self::SERVICE_LIST_173,
            self::SERVICE_LIST_174,
            self::SERVICE_LIST_175,
            self::SERVICE_LIST_176,
            self::SERVICE_LIST_177,
            self::SERVICE_LIST_178,
            self::SERVICE_LIST_179,
            self::SERVICE_LIST_180,
            self::SERVICE_LIST_181,
            self::SERVICE_LIST_182,
            self::SERVICE_LIST_183,
            self::SERVICE_LIST_184,
            self::SERVICE_LIST_185,
            self::SERVICE_LIST_186,
            self::SERVICE_LIST_187,
            self::SERVICE_LIST_188,
            self::SERVICE_LIST_189,
            self::SERVICE_LIST_190,
            self::SERVICE_LIST_191,
            self::SERVICE_LIST_192,
            self::SERVICE_LIST_193,
            self::SERVICE_LIST_194,
            self::SERVICE_LIST_195,
            self::SERVICE_LIST_196,
            self::SERVICE_LIST_197,
            self::SERVICE_LIST_198,
            self::SERVICE_LIST_199,
            self::SERVICE_LIST_200,
            self::SERVICE_LIST_201,
            self::SERVICE_LIST_202,
            self::SERVICE_LIST_203,
            self::SERVICE_LIST_204,
            self::SERVICE_LIST_205,
            self::SERVICE_LIST_206,
            self::SERVICE_LIST_207,
            self::SERVICE_LIST_208,
            self::SERVICE_LIST_209,
            self::SERVICE_LIST_210,
            self::SERVICE_LIST_211,
            self::SERVICE_LIST_212,
            self::SERVICE_LIST_213,
            self::SERVICE_LIST_214,
            self::SERVICE_LIST_215,
            self::SERVICE_LIST_216,
            self::SERVICE_LIST_217,
            self::SERVICE_LIST_218,
            self::SERVICE_LIST_219,
            self::SERVICE_LIST_220,
            self::SERVICE_LIST_221,
            self::SERVICE_LIST_222,
            self::SERVICE_LIST_223,
            self::SERVICE_LIST_224,
            self::SERVICE_LIST_225,
            self::SERVICE_LIST_226,
            self::SERVICE_LIST_227,
            self::SERVICE_LIST_228,
            self::SERVICE_LIST_229,
            self::SERVICE_LIST_230,
            self::SERVICE_LIST_231,
            self::SERVICE_LIST_232,
            self::SERVICE_LIST_233,
            self::SERVICE_LIST_234,
            self::SERVICE_LIST_235,
            self::SERVICE_LIST_236,
            self::SERVICE_LIST_237,
            self::SERVICE_LIST_238,
            self::SERVICE_LIST_239,
            self::SERVICE_LIST_240,
            self::SERVICE_LIST_241,
            self::SERVICE_LIST_242,
            self::SERVICE_LIST_243,
            self::SERVICE_LIST_244,
            self::SERVICE_LIST_245,
            self::SERVICE_LIST_246,
            self::SERVICE_LIST_247,
            self::SERVICE_LIST_248,
            self::SERVICE_LIST_249,
            self::SERVICE_LIST_250,
            self::SERVICE_LIST_251,
            self::SERVICE_LIST_252,
            self::SERVICE_LIST_253,
            self::SERVICE_LIST_254,
            self::SERVICE_LIST_255,
            self::SERVICE_LIST_256,
            self::SERVICE_LIST_257,
            self::SERVICE_LIST_258,
            self::SERVICE_LIST_259,
            self::SERVICE_LIST_260,
            self::SERVICE_LIST_261,
            self::SERVICE_LIST_262,
            self::SERVICE_LIST_263,
            self::SERVICE_LIST_264,
            self::SERVICE_LIST_265,
            self::SERVICE_LIST_266,
            self::SERVICE_LIST_267,
            self::SERVICE_LIST_268,
            self::SERVICE_LIST_269,
            self::SERVICE_LIST_270,
            self::SERVICE_LIST_271,
            self::SERVICE_LIST_272,
            self::SERVICE_LIST_273,
            self::SERVICE_LIST_274,
            self::SERVICE_LIST_275,
            self::SERVICE_LIST_276,
            self::SERVICE_LIST_277,
            self::SERVICE_LIST_278,
            self::SERVICE_LIST_279,
            self::SERVICE_LIST_280,
            self::SERVICE_LIST_281,
            self::SERVICE_LIST_282,
            self::SERVICE_LIST_283,
            self::SERVICE_LIST_284,
            self::SERVICE_LIST_285,
            self::SERVICE_LIST_286,
            self::SERVICE_LIST_287,
            self::SERVICE_LIST_288,
            self::SERVICE_LIST_289,
            self::SERVICE_LIST_290,
            self::SERVICE_LIST_291,
            self::SERVICE_LIST_292,
            self::SERVICE_LIST_293,
            self::SERVICE_LIST_294,
            self::SERVICE_LIST_295,
            self::SERVICE_LIST_296,
            self::SERVICE_LIST_297,
            self::SERVICE_LIST_298,
            self::SERVICE_LIST_299,
            self::SERVICE_LIST_300,
            self::SERVICE_LIST_301,
            self::SERVICE_LIST_302,
            self::SERVICE_LIST_303,
            self::SERVICE_LIST_304,
            self::SERVICE_LIST_305,
            self::SERVICE_LIST_306,
            self::SERVICE_LIST_307,
            self::SERVICE_LIST_308,
            self::SERVICE_LIST_309,
            self::SERVICE_LIST_310,
            self::SERVICE_LIST_311,
            self::SERVICE_LIST_312,
            self::SERVICE_LIST_313,
            self::SERVICE_LIST_314,
            self::SERVICE_LIST_315,
            self::SERVICE_LIST_316,
            self::SERVICE_LIST_317,
            self::SERVICE_LIST_318,
            self::SERVICE_LIST_319,
            self::SERVICE_LIST_320,
            self::SERVICE_LIST_321,
            self::SERVICE_LIST_322,
            self::SERVICE_LIST_323,
            self::SERVICE_LIST_324,
            self::SERVICE_LIST_325,
            self::SERVICE_LIST_326,
            self::SERVICE_LIST_327,
            self::SERVICE_LIST_328,
            self::SERVICE_LIST_329,
            self::SERVICE_LIST_331,
            self::SERVICE_LIST_332,
            self::SERVICE_LIST_333,
            self::SERVICE_LIST_334,
            self::SERVICE_LIST_335,
            self::SERVICE_LIST_336,
            self::SERVICE_LIST_337,
            self::SERVICE_LIST_338,
            self::SERVICE_LIST_339,
            self::SERVICE_LIST_340,
            self::SERVICE_LIST_341,
            self::SERVICE_LIST_342,
            self::SERVICE_LIST_343,
            self::SERVICE_LIST_344,
            self::SERVICE_LIST_345,
            self::SERVICE_LIST_348,
            self::SERVICE_LIST_349,
            self::SERVICE_LIST_350,
            self::SERVICE_LIST_351,
            self::SERVICE_LIST_5000,
            self::SERVICE_LIST_5001,
            self::SERVICE_LIST_5002,
            self::SERVICE_LIST_5003,
            self::SERVICE_LIST_5004,
            self::SERVICE_LIST_5005,
            self::SERVICE_LIST_5006,
            self::SERVICE_LIST_5007,
            self::SERVICE_LIST_5008,
            self::SERVICE_LIST_5009,
            self::SERVICE_LIST_5010,
            self::SERVICE_LIST_5011,
            self::SERVICE_LIST_5012,
            self::SERVICE_LIST_5013,
            self::SERVICE_LIST_5014,
            self::SERVICE_LIST_5015,
            self::SERVICE_LIST_5016,
            self::SERVICE_LIST_5017,
            self::SERVICE_LIST_5018,
            self::SERVICE_LIST_5020,
            self::SERVICE_LIST_5021,
            self::SERVICE_LIST_5022,
            self::SERVICE_LIST_5023,
            self::SERVICE_LIST_5024,
            self::SERVICE_LIST_5025,
            self::SERVICE_LIST_5026,
            self::SERVICE_LIST_5027,
            self::SERVICE_LIST_5028,
            self::SERVICE_LIST_5029,
            self::SERVICE_LIST_5030,
            self::SERVICE_LIST_5031,
            self::SERVICE_LIST_5032,
            self::SERVICE_LIST_5033,
            self::SERVICE_LIST_5034,
            self::SERVICE_LIST_5035,
            self::SERVICE_LIST_5036,
            self::SERVICE_LIST_5037,
            self::SERVICE_LIST_5039,
            self::SERVICE_LIST_5040,
            self::SERVICE_LIST_5041,
            self::SERVICE_LIST_5042,
            self::SERVICE_LIST_5043,
            self::SERVICE_LIST_5044,
            self::SERVICE_LIST_5045,
            self::SERVICE_LIST_5046,
            self::SERVICE_LIST_5047,
            self::SERVICE_LIST_5048,
            self::SERVICE_LIST_5049,
            self::SERVICE_LIST_5050,
            self::SERVICE_LIST_5051,
            self::SERVICE_LIST_5052,
            self::SERVICE_LIST_5053,
            self::SERVICE_LIST_5054,
            self::SERVICE_LIST_5055,
            self::SERVICE_LIST_5056,
            self::SERVICE_LIST_5057,
            self::SERVICE_LIST_5058,
            self::SERVICE_LIST_5059,
            self::SERVICE_LIST_5060,
            self::SERVICE_LIST_5061,
            self::SERVICE_LIST_5062,
            self::SERVICE_LIST_5063,
            self::SERVICE_LIST_5064,
            self::SERVICE_LIST_5065,
            self::SERVICE_LIST_5066,
            self::SERVICE_LIST_5067,
            self::SERVICE_LIST_5068,
            self::SERVICE_LIST_5069,
            self::SERVICE_LIST_5070,
            self::SERVICE_LIST_5071,
            self::SERVICE_LIST_5072,
            self::SERVICE_LIST_5073,
            self::SERVICE_LIST_5074,
            self::SERVICE_LIST_5075,
            self::SERVICE_LIST_5076,
            self::SERVICE_LIST_5077,
            self::SERVICE_LIST_5078,
            self::SERVICE_LIST_5079,
            self::SERVICE_LIST_5080,
            self::SERVICE_LIST_5081,
            self::SERVICE_LIST_5082,
            self::SERVICE_LIST_5083,
            self::SERVICE_LIST_5084,
            self::SERVICE_LIST_5085,
            self::SERVICE_LIST_5086,
            self::SERVICE_LIST_5087,
            self::SERVICE_LIST_5088,
            self::SERVICE_LIST_5089,
            self::SERVICE_LIST_5090,
            self::SERVICE_LIST_5091,
            self::SERVICE_LIST_5092,
            self::SERVICE_LIST_5093,
            self::SERVICE_LIST_5094,
            self::SERVICE_LIST_5095,
            self::SERVICE_LIST_5096,
            self::SERVICE_LIST_5097,
            self::SERVICE_LIST_5098,
            self::SERVICE_LIST_5099,
            self::SERVICE_LIST_5100,
            self::SERVICE_LIST_5101,
            self::SERVICE_LIST_5102,
            self::SERVICE_LIST_5103,
            self::SERVICE_LIST_5104,
            self::SERVICE_LIST_5105,
            self::SERVICE_LIST_5106,
            self::SERVICE_LIST_5107,
            self::SERVICE_LIST_5108,
            self::SERVICE_LIST_5109,
            self::SERVICE_LIST_5110,
            self::SERVICE_LIST_5111,
            self::SERVICE_LIST_5112,
            self::SERVICE_LIST_5113,
            self::SERVICE_LIST_5114,
            self::SERVICE_LIST_5115,
            self::SERVICE_LIST_5116,
            self::SERVICE_LIST_5117,
            self::SERVICE_LIST_5118,
            self::SERVICE_LIST_5119,
            self::SERVICE_LIST_5120,
            self::SERVICE_LIST_5121,
            self::SERVICE_LIST_5122,
            self::SERVICE_LIST_5123,
            self::SERVICE_LIST_5124,
            self::SERVICE_LIST_5125,
            self::SERVICE_LIST_5126,
            self::SERVICE_LIST_5127,
            self::SERVICE_LIST_5128,
            self::SERVICE_LIST_5129,
            self::SERVICE_LIST_5130,
            self::SERVICE_LIST_5131,
            self::SERVICE_LIST_5132,
            self::SERVICE_LIST_5133,
            self::SERVICE_LIST_5134,
            self::SERVICE_LIST_5135,
            self::SERVICE_LIST_5136,
            self::SERVICE_LIST_5137,
            self::SERVICE_LIST_5138,
            self::SERVICE_LIST_5139,
            self::SERVICE_LIST_5140,
            self::SERVICE_LIST_5141,
            self::SERVICE_LIST_5142,
            self::SERVICE_LIST_5143,
            self::SERVICE_LIST_5144,
            self::SERVICE_LIST_5145,
            self::SERVICE_LIST_5146,
            self::SERVICE_LIST_5147,
            self::SERVICE_LIST_5148,
            self::SERVICE_LIST_5149,
            self::SERVICE_LIST_5150,
            self::SERVICE_LIST_5151,
            self::SERVICE_LIST_5152,
            self::SERVICE_LIST_5153,
            self::SERVICE_LIST_5154,
            self::SERVICE_LIST_5156,
            self::SERVICE_LIST_5157,
            self::SERVICE_LIST_5158,
            self::SERVICE_LIST_5159,
            self::SERVICE_LIST_5160,
            self::SERVICE_LIST_5161,
            self::SERVICE_LIST_5162,
            self::SERVICE_LIST_5163,
            self::SERVICE_LIST_5164,
            self::SERVICE_LIST_5165,
            self::SERVICE_LIST_5166,
            self::SERVICE_LIST_5167,
            self::SERVICE_LIST_5168,
            self::SERVICE_LIST_5169,
            self::SERVICE_LIST_5170,
            self::SERVICE_LIST_5171,
            self::SERVICE_LIST_5172,
            self::SERVICE_LIST_5173,
            self::SERVICE_LIST_5174,
            self::SERVICE_LIST_5175,
            self::SERVICE_LIST_5176,
            self::SERVICE_LIST_5177,
            self::SERVICE_LIST_5178,
            self::SERVICE_LIST_6000,
            self::SERVICE_LIST_6001,
            self::SERVICE_LIST_90001,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCategoryListAllowableValues()
    {
        return [
            self::CATEGORY_LIST_1,
            self::CATEGORY_LIST_2,
            self::CATEGORY_LIST_3,
            self::CATEGORY_LIST_4,
            self::CATEGORY_LIST_5,
            self::CATEGORY_LIST_6,
            self::CATEGORY_LIST_7,
            self::CATEGORY_LIST_8,
            self::CATEGORY_LIST_9,
            self::CATEGORY_LIST_10,
            self::CATEGORY_LIST_11,
            self::CATEGORY_LIST_12,
            self::CATEGORY_LIST_13,
            self::CATEGORY_LIST_14,
            self::CATEGORY_LIST_15,
            self::CATEGORY_LIST_16,
            self::CATEGORY_LIST_17,
            self::CATEGORY_LIST_18,
            self::CATEGORY_LIST_19,
            self::CATEGORY_LIST_20,
            self::CATEGORY_LIST_21,
            self::CATEGORY_LIST_22,
            self::CATEGORY_LIST_23,
            self::CATEGORY_LIST_24,
            self::CATEGORY_LIST_25,
            self::CATEGORY_LIST_26,
            self::CATEGORY_LIST_27,
            self::CATEGORY_LIST_28,
            self::CATEGORY_LIST_29,
            self::CATEGORY_LIST_30,
            self::CATEGORY_LIST_31,
            self::CATEGORY_LIST_32,
            self::CATEGORY_LIST_33,
            self::CATEGORY_LIST_34,
            self::CATEGORY_LIST_35,
            self::CATEGORY_LIST_36,
            self::CATEGORY_LIST_37,
            self::CATEGORY_LIST_38,
            self::CATEGORY_LIST_39,
            self::CATEGORY_LIST_40,
            self::CATEGORY_LIST_41,
            self::CATEGORY_LIST_42,
            self::CATEGORY_LIST_43,
            self::CATEGORY_LIST_44,
            self::CATEGORY_LIST_45,
            self::CATEGORY_LIST_46,
            self::CATEGORY_LIST_47,
            self::CATEGORY_LIST_48,
            self::CATEGORY_LIST_49,
            self::CATEGORY_LIST_50,
            self::CATEGORY_LIST_51,
            self::CATEGORY_LIST_52,
            self::CATEGORY_LIST_53,
            self::CATEGORY_LIST_54,
            self::CATEGORY_LIST_55,
            self::CATEGORY_LIST_56,
            self::CATEGORY_LIST_57,
            self::CATEGORY_LIST_58,
            self::CATEGORY_LIST_59,
            self::CATEGORY_LIST_60,
            self::CATEGORY_LIST_61,
            self::CATEGORY_LIST_62,
            self::CATEGORY_LIST_5000,
            self::CATEGORY_LIST_5001,
            self::CATEGORY_LIST_5002,
            self::CATEGORY_LIST_5003,
            self::CATEGORY_LIST_5004,
            self::CATEGORY_LIST_5005,
            self::CATEGORY_LIST_5006,
            self::CATEGORY_LIST_5007,
            self::CATEGORY_LIST_5008,
            self::CATEGORY_LIST_5009,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['code'] = $data['code'] ?? null;
        $this->container['language_code'] = $data['language_code'] ?? null;
        $this->container['currency_code'] = $data['currency_code'] ?? null;
        $this->container['unit_system'] = $data['unit_system'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['uri'] = $data['uri'] ?? null;
        $this->container['service_list'] = $data['service_list'] ?? null;
        $this->container['category_list'] = $data['category_list'] ?? null;
        $this->container['uri_path'] = $data['uri_path'] ?? null;
        $this->container['text'] = $data['text'] ?? null;
        $this->container['geo'] = $data['geo'] ?? null;
        $this->container['media_list'] = $data['media_list'] ?? null;
        $this->container['attraction_list'] = $data['attraction_list'] ?? null;
        $this->container['lowest_price'] = $data['lowest_price'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ($this->container['language_code'] === null) {
            $invalidProperties[] = "'language_code' can't be null";
        }
        if ($this->container['currency_code'] === null) {
            $invalidProperties[] = "'currency_code' can't be null";
        }
        if ($this->container['unit_system'] === null) {
            $invalidProperties[] = "'unit_system' can't be null";
        }
        $allowedValues = $this->getUnitSystemAllowableValues();
        if (!is_null($this->container['unit_system']) && !in_array($this->container['unit_system'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'unit_system', must be one of '%s'",
                $this->container['unit_system'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['uri'] === null) {
            $invalidProperties[] = "'uri' can't be null";
        }
        if ($this->container['service_list'] === null) {
            $invalidProperties[] = "'service_list' can't be null";
        }
        if ($this->container['category_list'] === null) {
            $invalidProperties[] = "'category_list' can't be null";
        }
        if ($this->container['uri_path'] === null) {
            $invalidProperties[] = "'uri_path' can't be null";
        }
        if ($this->container['text'] === null) {
            $invalidProperties[] = "'text' can't be null";
        }
        if ($this->container['media_list'] === null) {
            $invalidProperties[] = "'media_list' can't be null";
        }
        if ($this->container['attraction_list'] === null) {
            $invalidProperties[] = "'attraction_list' can't be null";
        }
        if ($this->container['lowest_price'] === null) {
            $invalidProperties[] = "'lowest_price' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code The properties unique code/ID.
     *
     * @return self
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets language_code
     *
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->container['language_code'];
    }

    /**
     * Sets language_code
     *
     * @param string $language_code The language code of the language in which the property description is written.<p>Please note that beside the general restrictions listed below only languages configured during system setup for your respective tenant are allowed.</p><p>See also <a href=\"#isolanguage-codes\">in the appendix</a>.</p>
     *
     * @return self
     */
    public function setLanguageCode($language_code)
    {
        $this->container['language_code'] = $language_code;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string $currency_code The currency code for the currency in which prices are returned.<p>See also <a href=\"#currencycodes\">in the appendix</a>.</p>
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {
        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets unit_system
     *
     * @return string
     */
    public function getUnitSystem()
    {
        return $this->container['unit_system'];
    }

    /**
     * Sets unit_system
     *
     * @param string $unit_system The unit system (either \"metric\" or \"imperial\") used for measurements.
     *
     * @return self
     */
    public function setUnitSystem($unit_system)
    {
        $allowedValues = $this->getUnitSystemAllowableValues();
        if (!in_array($unit_system, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'unit_system', must be one of '%s'",
                    $unit_system,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['unit_system'] = $unit_system;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the property.
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets uri
     *
     * @return string
     */
    public function getUri()
    {
        return $this->container['uri'];
    }

    /**
     * Sets uri
     *
     * @param string $uri A URI for the property.
     *
     * @return self
     */
    public function setUri($uri)
    {
        $this->container['uri'] = $uri;

        return $this;
    }

    /**
     * Gets service_list
     *
     * @return float[]
     */
    public function getServiceList()
    {
        return $this->container['service_list'];
    }

    /**
     * Sets service_list
     *
     * @param float[] $service_list A list of service codes indicating the services and amenities the property has.<p>See also <a href=\"#servicecodes\">in the appendix</a>.</p>
     *
     * @return self
     */
    public function setServiceList($service_list)
    {
        $allowedValues = $this->getServiceListAllowableValues();
        if (array_diff($service_list, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'service_list', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['service_list'] = $service_list;

        return $this;
    }

    /**
     * Gets category_list
     *
     * @return float[]
     */
    public function getCategoryList()
    {
        return $this->container['category_list'];
    }

    /**
     * Sets category_list
     *
     * @param float[] $category_list A list of property class type codes indicating the types of the property.<p>See also <a href=\"#propertyclass-type-codes\">in the appendix</a>.</p>
     *
     * @return self
     */
    public function setCategoryList($category_list)
    {
        $allowedValues = $this->getCategoryListAllowableValues();
        if (array_diff($category_list, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'category_list', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['category_list'] = $category_list;

        return $this;
    }

    /**
     * Gets uri_path
     *
     * @return string
     */
    public function getUriPath()
    {
        return $this->container['uri_path'];
    }

    /**
     * Sets uri_path
     *
     * @param string $uri_path A URI path for the property.
     *
     * @return self
     */
    public function setUriPath($uri_path)
    {
        $this->container['uri_path'] = $uri_path;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string $text A description of the property.
     *
     * @return self
     */
    public function setText($text)
    {
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets geo
     *
     * @return \com.lodgea\com.lodgea.model\InlineResponse2001Geo|null
     */
    public function getGeo()
    {
        return $this->container['geo'];
    }

    /**
     * Sets geo
     *
     * @param \com.lodgea\com.lodgea.model\InlineResponse2001Geo|null $geo geo
     *
     * @return self
     */
    public function setGeo($geo)
    {
        $this->container['geo'] = $geo;

        return $this;
    }

    /**
     * Gets media_list
     *
     * @return \com.lodgea\com.lodgea.model\InlineResponse2001MediaList[]
     */
    public function getMediaList()
    {
        return $this->container['media_list'];
    }

    /**
     * Sets media_list
     *
     * @param \com.lodgea\com.lodgea.model\InlineResponse2001MediaList[] $media_list A list of media objects for the property.
     *
     * @return self
     */
    public function setMediaList($media_list)
    {
        $this->container['media_list'] = $media_list;

        return $this;
    }

    /**
     * Gets attraction_list
     *
     * @return \com.lodgea\com.lodgea.model\InlineResponse2001AttractionList[]
     */
    public function getAttractionList()
    {
        return $this->container['attraction_list'];
    }

    /**
     * Sets attraction_list
     *
     * @param \com.lodgea\com.lodgea.model\InlineResponse2001AttractionList[] $attraction_list A list of objects describing the attractions available at the property.
     *
     * @return self
     */
    public function setAttractionList($attraction_list)
    {
        $this->container['attraction_list'] = $attraction_list;

        return $this;
    }

    /**
     * Gets lowest_price
     *
     * @return \com.lodgea\com.lodgea.model\InlineResponse2001LowestPrice
     */
    public function getLowestPrice()
    {
        return $this->container['lowest_price'];
    }

    /**
     * Sets lowest_price
     *
     * @param \com.lodgea\com.lodgea.model\InlineResponse2001LowestPrice $lowest_price lowest_price
     *
     * @return self
     */
    public function setLowestPrice($lowest_price)
    {
        $this->container['lowest_price'] = $lowest_price;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


