<?php
/**
 * InlineResponse2003ProductList
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  com.lodgea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lodgea-php
 *
 * LODGEA SDK for php. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com.lodgea\com.lodgea.model;

use \ArrayAccess;
use \com.lodgea\ObjectSerializer;

/**
 * InlineResponse2003ProductList Class Doc Comment
 *
 * @category Class
 * @description A list of available products for this property.
 * @package  com.lodgea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class InlineResponse2003ProductList implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_3_productList';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'property_id' => 'string',
        'name' => 'string',
        'meal_plan_list' => 'float[]',
        'room_type_list' => 'string[]',
        'is_los_pricing' => 'bool',
        'is_obp_pricing' => 'bool',
        'rate_plan_list' => '\com.lodgea\com.lodgea.model\InlineResponse2003RatePlanList[]',
        'policy_info' => '\com.lodgea\com.lodgea.model\InlineResponse2003PolicyInfo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'property_id' => null,
        'name' => null,
        'meal_plan_list' => null,
        'room_type_list' => null,
        'is_los_pricing' => null,
        'is_obp_pricing' => null,
        'rate_plan_list' => null,
        'policy_info' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'property_id' => 'propertyId',
        'name' => 'name',
        'meal_plan_list' => 'mealPlanList',
        'room_type_list' => 'roomTypeList',
        'is_los_pricing' => 'isLOSPricing',
        'is_obp_pricing' => 'isOBPPricing',
        'rate_plan_list' => 'ratePlanList',
        'policy_info' => 'policyInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'property_id' => 'setPropertyId',
        'name' => 'setName',
        'meal_plan_list' => 'setMealPlanList',
        'room_type_list' => 'setRoomTypeList',
        'is_los_pricing' => 'setIsLosPricing',
        'is_obp_pricing' => 'setIsObpPricing',
        'rate_plan_list' => 'setRatePlanList',
        'policy_info' => 'setPolicyInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'property_id' => 'getPropertyId',
        'name' => 'getName',
        'meal_plan_list' => 'getMealPlanList',
        'room_type_list' => 'getRoomTypeList',
        'is_los_pricing' => 'getIsLosPricing',
        'is_obp_pricing' => 'getIsObpPricing',
        'rate_plan_list' => 'getRatePlanList',
        'policy_info' => 'getPolicyInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const MEAL_PLAN_LIST_0 = 0;
    const MEAL_PLAN_LIST_1 = 1;
    const MEAL_PLAN_LIST_2 = 2;
    const MEAL_PLAN_LIST_3 = 3;
    const MEAL_PLAN_LIST_4 = 4;
    const MEAL_PLAN_LIST_5 = 5;
    const MEAL_PLAN_LIST_6 = 6;
    const MEAL_PLAN_LIST_7 = 7;
    const MEAL_PLAN_LIST_8 = 8;
    const MEAL_PLAN_LIST_9 = 9;
    const MEAL_PLAN_LIST_10 = 10;
    const MEAL_PLAN_LIST_11 = 11;
    const MEAL_PLAN_LIST_12 = 12;
    const MEAL_PLAN_LIST_14 = 14;
    const MEAL_PLAN_LIST_15 = 15;
    const MEAL_PLAN_LIST_16 = 16;
    const MEAL_PLAN_LIST_17 = 17;
    const MEAL_PLAN_LIST_18 = 18;
    const MEAL_PLAN_LIST_19 = 19;
    const MEAL_PLAN_LIST_20 = 20;
    const MEAL_PLAN_LIST_21 = 21;
    const MEAL_PLAN_LIST_22 = 22;
    const MEAL_PLAN_LIST_23 = 23;
    const MEAL_PLAN_LIST_24 = 24;
    const MEAL_PLAN_LIST_90001 = 90001;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMealPlanListAllowableValues()
    {
        return [
            self::MEAL_PLAN_LIST_0,
            self::MEAL_PLAN_LIST_1,
            self::MEAL_PLAN_LIST_2,
            self::MEAL_PLAN_LIST_3,
            self::MEAL_PLAN_LIST_4,
            self::MEAL_PLAN_LIST_5,
            self::MEAL_PLAN_LIST_6,
            self::MEAL_PLAN_LIST_7,
            self::MEAL_PLAN_LIST_8,
            self::MEAL_PLAN_LIST_9,
            self::MEAL_PLAN_LIST_10,
            self::MEAL_PLAN_LIST_11,
            self::MEAL_PLAN_LIST_12,
            self::MEAL_PLAN_LIST_14,
            self::MEAL_PLAN_LIST_15,
            self::MEAL_PLAN_LIST_16,
            self::MEAL_PLAN_LIST_17,
            self::MEAL_PLAN_LIST_18,
            self::MEAL_PLAN_LIST_19,
            self::MEAL_PLAN_LIST_20,
            self::MEAL_PLAN_LIST_21,
            self::MEAL_PLAN_LIST_22,
            self::MEAL_PLAN_LIST_23,
            self::MEAL_PLAN_LIST_24,
            self::MEAL_PLAN_LIST_90001,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['property_id'] = $data['property_id'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['meal_plan_list'] = $data['meal_plan_list'] ?? null;
        $this->container['room_type_list'] = $data['room_type_list'] ?? null;
        $this->container['is_los_pricing'] = $data['is_los_pricing'] ?? null;
        $this->container['is_obp_pricing'] = $data['is_obp_pricing'] ?? null;
        $this->container['rate_plan_list'] = $data['rate_plan_list'] ?? null;
        $this->container['policy_info'] = $data['policy_info'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['property_id'] === null) {
            $invalidProperties[] = "'property_id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['meal_plan_list'] === null) {
            $invalidProperties[] = "'meal_plan_list' can't be null";
        }
        if ($this->container['room_type_list'] === null) {
            $invalidProperties[] = "'room_type_list' can't be null";
        }
        if ($this->container['rate_plan_list'] === null) {
            $invalidProperties[] = "'rate_plan_list' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets property_id
     *
     * @return string
     */
    public function getPropertyId()
    {
        return $this->container['property_id'];
    }

    /**
     * Sets property_id
     *
     * @param string $property_id The ID of the property.
     *
     * @return self
     */
    public function setPropertyId($property_id)
    {
        $this->container['property_id'] = $property_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the product.
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets meal_plan_list
     *
     * @return float[]
     */
    public function getMealPlanList()
    {
        return $this->container['meal_plan_list'];
    }

    /**
     * Sets meal_plan_list
     *
     * @param float[] $meal_plan_list A list of meal type codes included in this product.
     *
     * @return self
     */
    public function setMealPlanList($meal_plan_list)
    {
        $allowedValues = $this->getMealPlanListAllowableValues();
        if (array_diff($meal_plan_list, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'meal_plan_list', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['meal_plan_list'] = $meal_plan_list;

        return $this;
    }

    /**
     * Gets room_type_list
     *
     * @return string[]
     */
    public function getRoomTypeList()
    {
        return $this->container['room_type_list'];
    }

    /**
     * Sets room_type_list
     *
     * @param string[] $room_type_list An array of strings describing the room types included in this product.
     *
     * @return self
     */
    public function setRoomTypeList($room_type_list)
    {
        $this->container['room_type_list'] = $room_type_list;

        return $this;
    }

    /**
     * Gets is_los_pricing
     *
     * @return bool|null
     */
    public function getIsLosPricing()
    {
        return $this->container['is_los_pricing'];
    }

    /**
     * Sets is_los_pricing
     *
     * @param bool|null $is_los_pricing Whether this product is length of stay pricing.
     *
     * @return self
     */
    public function setIsLosPricing($is_los_pricing)
    {
        $this->container['is_los_pricing'] = $is_los_pricing;

        return $this;
    }

    /**
     * Gets is_obp_pricing
     *
     * @return bool|null
     */
    public function getIsObpPricing()
    {
        return $this->container['is_obp_pricing'];
    }

    /**
     * Sets is_obp_pricing
     *
     * @param bool|null $is_obp_pricing Whether this product is occupancy based pricing.
     *
     * @return self
     */
    public function setIsObpPricing($is_obp_pricing)
    {
        $this->container['is_obp_pricing'] = $is_obp_pricing;

        return $this;
    }

    /**
     * Gets rate_plan_list
     *
     * @return \com.lodgea\com.lodgea.model\InlineResponse2003RatePlanList[]
     */
    public function getRatePlanList()
    {
        return $this->container['rate_plan_list'];
    }

    /**
     * Sets rate_plan_list
     *
     * @param \com.lodgea\com.lodgea.model\InlineResponse2003RatePlanList[] $rate_plan_list The rate plans for this product.
     *
     * @return self
     */
    public function setRatePlanList($rate_plan_list)
    {
        $this->container['rate_plan_list'] = $rate_plan_list;

        return $this;
    }

    /**
     * Gets policy_info
     *
     * @return \com.lodgea\com.lodgea.model\InlineResponse2003PolicyInfo|null
     */
    public function getPolicyInfo()
    {
        return $this->container['policy_info'];
    }

    /**
     * Sets policy_info
     *
     * @param \com.lodgea\com.lodgea.model\InlineResponse2003PolicyInfo|null $policy_info policy_info
     *
     * @return self
     */
    public function setPolicyInfo($policy_info)
    {
        $this->container['policy_info'] = $policy_info;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


