<?php
/**
 * PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com.lodgea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lodgea-php
 *
 * LODGEA SDK for PHP. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com.lodgea\com.lodgea.model;

use \ArrayAccess;
use \com.lodgea\ObjectSerializer;

/**
 * PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner Class Doc Comment
 *
 * @category Class
 * @package  com.lodgea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerTaxPolicyListInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_properties__propertyId__get_200_response_property_policyList_inner_taxPolicyList_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type_code' => 'float',
        'percent' => 'float',
        'charge_type' => 'string',
        'charge_frequency_code' => 'float',
        'currency_code' => 'string',
        'condition_list' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type_code' => null,
        'percent' => null,
        'charge_type' => null,
        'charge_frequency_code' => null,
        'currency_code' => null,
        'condition_list' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type_code' => 'typeCode',
        'percent' => 'percent',
        'charge_type' => 'chargeType',
        'charge_frequency_code' => 'chargeFrequencyCode',
        'currency_code' => 'currencyCode',
        'condition_list' => 'conditionList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type_code' => 'setTypeCode',
        'percent' => 'setPercent',
        'charge_type' => 'setChargeType',
        'charge_frequency_code' => 'setChargeFrequencyCode',
        'currency_code' => 'setCurrencyCode',
        'condition_list' => 'setConditionList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type_code' => 'getTypeCode',
        'percent' => 'getPercent',
        'charge_type' => 'getChargeType',
        'charge_frequency_code' => 'getChargeFrequencyCode',
        'currency_code' => 'getCurrencyCode',
        'condition_list' => 'getConditionList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_CODE_1 = 1;
    public const TYPE_CODE_3 = 3;
    public const TYPE_CODE_4 = 4;
    public const TYPE_CODE_5 = 5;
    public const TYPE_CODE_6 = 6;
    public const TYPE_CODE_7 = 7;
    public const TYPE_CODE_8 = 8;
    public const TYPE_CODE_10 = 10;
    public const TYPE_CODE_13 = 13;
    public const TYPE_CODE_15 = 15;
    public const TYPE_CODE_17 = 17;
    public const TYPE_CODE_18 = 18;
    public const TYPE_CODE_19 = 19;
    public const TYPE_CODE_28 = 28;
    public const TYPE_CODE_30 = 30;
    public const TYPE_CODE_35 = 35;
    public const TYPE_CODE_36 = 36;
    public const TYPE_CODE_39 = 39;
    public const TYPE_CODE_43 = 43;
    public const TYPE_CODE_46 = 46;
    public const TYPE_CODE_5001 = 5001;
    public const TYPE_CODE_5002 = 5002;
    public const TYPE_CODE_5004 = 5004;
    public const TYPE_CODE_5007 = 5007;
    public const TYPE_CODE_5008 = 5008;
    public const CHARGE_TYPE_INCLUDED = 'included';
    public const CHARGE_TYPE_EXCLUDED = 'excluded';
    public const CHARGE_TYPE_CONDITIONAL = 'conditional';
    public const CHARGE_FREQUENCY_CODE_1 = 1;
    public const CHARGE_FREQUENCY_CODE_2 = 2;
    public const CHARGE_FREQUENCY_CODE_7 = 7;
    public const CHARGE_FREQUENCY_CODE_10 = 10;
    public const CHARGE_FREQUENCY_CODE_12 = 12;
    public const CHARGE_FREQUENCY_CODE_17 = 17;
    public const CHARGE_FREQUENCY_CODE_19 = 19;
    public const CHARGE_FREQUENCY_CODE_20 = 20;
    public const CHARGE_FREQUENCY_CODE_21 = 21;
    public const CHARGE_FREQUENCY_CODE_25 = 25;
    public const CHARGE_FREQUENCY_CODE_31 = 31;
    public const CHARGE_FREQUENCY_CODE_5000 = 5000;
    public const CHARGE_FREQUENCY_CODE_5001 = 5001;
    public const CHARGE_FREQUENCY_CODE_5002 = 5002;
    public const CHARGE_FREQUENCY_CODE_5010 = 5010;
    public const CHARGE_FREQUENCY_CODE_5011 = 5011;
    public const CHARGE_FREQUENCY_CODE_5012 = 5012;
    public const CHARGE_FREQUENCY_CODE_5013 = 5013;
    public const CHARGE_FREQUENCY_CODE_5014 = 5014;
    public const CHARGE_FREQUENCY_CODE_5015 = 5015;
    public const CHARGE_FREQUENCY_CODE_5016 = 5016;
    public const CHARGE_FREQUENCY_CODE_5017 = 5017;
    public const CHARGE_FREQUENCY_CODE_90010 = 90010;
    public const CHARGE_FREQUENCY_CODE_90011 = 90011;
    public const CHARGE_FREQUENCY_CODE_90012 = 90012;
    public const CHARGE_FREQUENCY_CODE_90013 = 90013;
    public const CURRENCY_CODE_AED = 'AED';
    public const CURRENCY_CODE_ARS = 'ARS';
    public const CURRENCY_CODE_AUD = 'AUD';
    public const CURRENCY_CODE_AZN = 'AZN';
    public const CURRENCY_CODE_BGN = 'BGN';
    public const CURRENCY_CODE_BHD = 'BHD';
    public const CURRENCY_CODE_BRL = 'BRL';
    public const CURRENCY_CODE_CAD = 'CAD';
    public const CURRENCY_CODE_CHF = 'CHF';
    public const CURRENCY_CODE_CLP = 'CLP';
    public const CURRENCY_CODE_CNY = 'CNY';
    public const CURRENCY_CODE_COP = 'COP';
    public const CURRENCY_CODE_CZK = 'CZK';
    public const CURRENCY_CODE_DKK = 'DKK';
    public const CURRENCY_CODE_EGP = 'EGP';
    public const CURRENCY_CODE_EUR = 'EUR';
    public const CURRENCY_CODE_FJD = 'FJD';
    public const CURRENCY_CODE_GBP = 'GBP';
    public const CURRENCY_CODE_GEL = 'GEL';
    public const CURRENCY_CODE_HKD = 'HKD';
    public const CURRENCY_CODE_HUF = 'HUF';
    public const CURRENCY_CODE_IDR = 'IDR';
    public const CURRENCY_CODE_ILS = 'ILS';
    public const CURRENCY_CODE_INR = 'INR';
    public const CURRENCY_CODE_JOD = 'JOD';
    public const CURRENCY_CODE_JPY = 'JPY';
    public const CURRENCY_CODE_KRW = 'KRW';
    public const CURRENCY_CODE_KWD = 'KWD';
    public const CURRENCY_CODE_KZT = 'KZT';
    public const CURRENCY_CODE_MDL = 'MDL';
    public const CURRENCY_CODE_MXN = 'MXN';
    public const CURRENCY_CODE_MYR = 'MYR';
    public const CURRENCY_CODE_NAD = 'NAD';
    public const CURRENCY_CODE_NOK = 'NOK';
    public const CURRENCY_CODE_NZD = 'NZD';
    public const CURRENCY_CODE_OMR = 'OMR';
    public const CURRENCY_CODE_PLN = 'PLN';
    public const CURRENCY_CODE_QAR = 'QAR';
    public const CURRENCY_CODE_RON = 'RON';
    public const CURRENCY_CODE_RUB = 'RUB';
    public const CURRENCY_CODE_SAR = 'SAR';
    public const CURRENCY_CODE_SEK = 'SEK';
    public const CURRENCY_CODE_SGD = 'SGD';
    public const CURRENCY_CODE_THB = 'THB';
    public const CURRENCY_CODE__TRY = 'TRY';
    public const CURRENCY_CODE_TWD = 'TWD';
    public const CURRENCY_CODE_UAH = 'UAH';
    public const CURRENCY_CODE_USD = 'USD';
    public const CURRENCY_CODE_XOF = 'XOF';
    public const CURRENCY_CODE_ZAR = 'ZAR';
    public const CONDITION_LIST_BRINGS_PET = 'guest_brings_pet';
    public const CONDITION_LIST_DOESNT_CLEAN_BEFORE_CHECKOUT = 'guest_doesnt_clean_before_checkout';
    public const CONDITION_LIST_SMOKES = 'guest_smokes';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeCodeAllowableValues()
    {
        return [
            self::TYPE_CODE_1,
            self::TYPE_CODE_3,
            self::TYPE_CODE_4,
            self::TYPE_CODE_5,
            self::TYPE_CODE_6,
            self::TYPE_CODE_7,
            self::TYPE_CODE_8,
            self::TYPE_CODE_10,
            self::TYPE_CODE_13,
            self::TYPE_CODE_15,
            self::TYPE_CODE_17,
            self::TYPE_CODE_18,
            self::TYPE_CODE_19,
            self::TYPE_CODE_28,
            self::TYPE_CODE_30,
            self::TYPE_CODE_35,
            self::TYPE_CODE_36,
            self::TYPE_CODE_39,
            self::TYPE_CODE_43,
            self::TYPE_CODE_46,
            self::TYPE_CODE_5001,
            self::TYPE_CODE_5002,
            self::TYPE_CODE_5004,
            self::TYPE_CODE_5007,
            self::TYPE_CODE_5008,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChargeTypeAllowableValues()
    {
        return [
            self::CHARGE_TYPE_INCLUDED,
            self::CHARGE_TYPE_EXCLUDED,
            self::CHARGE_TYPE_CONDITIONAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChargeFrequencyCodeAllowableValues()
    {
        return [
            self::CHARGE_FREQUENCY_CODE_1,
            self::CHARGE_FREQUENCY_CODE_2,
            self::CHARGE_FREQUENCY_CODE_7,
            self::CHARGE_FREQUENCY_CODE_10,
            self::CHARGE_FREQUENCY_CODE_12,
            self::CHARGE_FREQUENCY_CODE_17,
            self::CHARGE_FREQUENCY_CODE_19,
            self::CHARGE_FREQUENCY_CODE_20,
            self::CHARGE_FREQUENCY_CODE_21,
            self::CHARGE_FREQUENCY_CODE_25,
            self::CHARGE_FREQUENCY_CODE_31,
            self::CHARGE_FREQUENCY_CODE_5000,
            self::CHARGE_FREQUENCY_CODE_5001,
            self::CHARGE_FREQUENCY_CODE_5002,
            self::CHARGE_FREQUENCY_CODE_5010,
            self::CHARGE_FREQUENCY_CODE_5011,
            self::CHARGE_FREQUENCY_CODE_5012,
            self::CHARGE_FREQUENCY_CODE_5013,
            self::CHARGE_FREQUENCY_CODE_5014,
            self::CHARGE_FREQUENCY_CODE_5015,
            self::CHARGE_FREQUENCY_CODE_5016,
            self::CHARGE_FREQUENCY_CODE_5017,
            self::CHARGE_FREQUENCY_CODE_90010,
            self::CHARGE_FREQUENCY_CODE_90011,
            self::CHARGE_FREQUENCY_CODE_90012,
            self::CHARGE_FREQUENCY_CODE_90013,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCurrencyCodeAllowableValues()
    {
        return [
            self::CURRENCY_CODE_AED,
            self::CURRENCY_CODE_ARS,
            self::CURRENCY_CODE_AUD,
            self::CURRENCY_CODE_AZN,
            self::CURRENCY_CODE_BGN,
            self::CURRENCY_CODE_BHD,
            self::CURRENCY_CODE_BRL,
            self::CURRENCY_CODE_CAD,
            self::CURRENCY_CODE_CHF,
            self::CURRENCY_CODE_CLP,
            self::CURRENCY_CODE_CNY,
            self::CURRENCY_CODE_COP,
            self::CURRENCY_CODE_CZK,
            self::CURRENCY_CODE_DKK,
            self::CURRENCY_CODE_EGP,
            self::CURRENCY_CODE_EUR,
            self::CURRENCY_CODE_FJD,
            self::CURRENCY_CODE_GBP,
            self::CURRENCY_CODE_GEL,
            self::CURRENCY_CODE_HKD,
            self::CURRENCY_CODE_HUF,
            self::CURRENCY_CODE_IDR,
            self::CURRENCY_CODE_ILS,
            self::CURRENCY_CODE_INR,
            self::CURRENCY_CODE_JOD,
            self::CURRENCY_CODE_JPY,
            self::CURRENCY_CODE_KRW,
            self::CURRENCY_CODE_KWD,
            self::CURRENCY_CODE_KZT,
            self::CURRENCY_CODE_MDL,
            self::CURRENCY_CODE_MXN,
            self::CURRENCY_CODE_MYR,
            self::CURRENCY_CODE_NAD,
            self::CURRENCY_CODE_NOK,
            self::CURRENCY_CODE_NZD,
            self::CURRENCY_CODE_OMR,
            self::CURRENCY_CODE_PLN,
            self::CURRENCY_CODE_QAR,
            self::CURRENCY_CODE_RON,
            self::CURRENCY_CODE_RUB,
            self::CURRENCY_CODE_SAR,
            self::CURRENCY_CODE_SEK,
            self::CURRENCY_CODE_SGD,
            self::CURRENCY_CODE_THB,
            self::CURRENCY_CODE__TRY,
            self::CURRENCY_CODE_TWD,
            self::CURRENCY_CODE_UAH,
            self::CURRENCY_CODE_USD,
            self::CURRENCY_CODE_XOF,
            self::CURRENCY_CODE_ZAR,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getConditionListAllowableValues()
    {
        return [
            self::CONDITION_LIST_BRINGS_PET,
            self::CONDITION_LIST_DOESNT_CLEAN_BEFORE_CHECKOUT,
            self::CONDITION_LIST_SMOKES,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type_code'] = $data['type_code'] ?? null;
        $this->container['percent'] = $data['percent'] ?? null;
        $this->container['charge_type'] = $data['charge_type'] ?? null;
        $this->container['charge_frequency_code'] = $data['charge_frequency_code'] ?? null;
        $this->container['currency_code'] = $data['currency_code'] ?? null;
        $this->container['condition_list'] = $data['condition_list'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type_code'] === null) {
            $invalidProperties[] = "'type_code' can't be null";
        }
        $allowedValues = $this->getTypeCodeAllowableValues();
        if (!is_null($this->container['type_code']) && !in_array($this->container['type_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type_code', must be one of '%s'",
                $this->container['type_code'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['charge_type'] === null) {
            $invalidProperties[] = "'charge_type' can't be null";
        }
        $allowedValues = $this->getChargeTypeAllowableValues();
        if (!is_null($this->container['charge_type']) && !in_array($this->container['charge_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'charge_type', must be one of '%s'",
                $this->container['charge_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['charge_frequency_code'] === null) {
            $invalidProperties[] = "'charge_frequency_code' can't be null";
        }
        $allowedValues = $this->getChargeFrequencyCodeAllowableValues();
        if (!is_null($this->container['charge_frequency_code']) && !in_array($this->container['charge_frequency_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'charge_frequency_code', must be one of '%s'",
                $this->container['charge_frequency_code'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['currency_code'] === null) {
            $invalidProperties[] = "'currency_code' can't be null";
        }
        $allowedValues = $this->getCurrencyCodeAllowableValues();
        if (!is_null($this->container['currency_code']) && !in_array($this->container['currency_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'currency_code', must be one of '%s'",
                $this->container['currency_code'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['condition_list'] === null) {
            $invalidProperties[] = "'condition_list' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type_code
     *
     * @return float
     */
    public function getTypeCode()
    {
        return $this->container['type_code'];
    }

    /**
     * Sets type_code
     *
     * @param float $type_code The code that represents the type of tax.<p>See also <a href=\"#taxtype-codes\">in the appendix</a>.</p>
     *
     * @return self
     */
    public function setTypeCode($type_code)
    {
        $allowedValues = $this->getTypeCodeAllowableValues();
        if (!in_array($type_code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type_code', must be one of '%s'",
                    $type_code,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type_code'] = $type_code;

        return $this;
    }

    /**
     * Gets percent
     *
     * @return float|null
     */
    public function getPercent()
    {
        return $this->container['percent'];
    }

    /**
     * Sets percent
     *
     * @param float|null $percent The charged percentage if applicable.
     *
     * @return self
     */
    public function setPercent($percent)
    {
        $this->container['percent'] = $percent;

        return $this;
    }

    /**
     * Gets charge_type
     *
     * @return string
     */
    public function getChargeType()
    {
        return $this->container['charge_type'];
    }

    /**
     * Sets charge_type
     *
     * @param string $charge_type The type of charge.
     *
     * @return self
     */
    public function setChargeType($charge_type)
    {
        $allowedValues = $this->getChargeTypeAllowableValues();
        if (!in_array($charge_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'charge_type', must be one of '%s'",
                    $charge_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['charge_type'] = $charge_type;

        return $this;
    }

    /**
     * Gets charge_frequency_code
     *
     * @return float
     */
    public function getChargeFrequencyCode()
    {
        return $this->container['charge_frequency_code'];
    }

    /**
     * Sets charge_frequency_code
     *
     * @param float $charge_frequency_code The code that represents the frequency of charge.<p>See also <a href=\"#chargetype-codes\">in the appendix</a>.</p>
     *
     * @return self
     */
    public function setChargeFrequencyCode($charge_frequency_code)
    {
        $allowedValues = $this->getChargeFrequencyCodeAllowableValues();
        if (!in_array($charge_frequency_code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'charge_frequency_code', must be one of '%s'",
                    $charge_frequency_code,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['charge_frequency_code'] = $charge_frequency_code;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string $currency_code The currency code of the currency in that the charge is applied.<p>See also <a href=\"#currencycodes\">in the appendix</a>.</p>
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {
        $allowedValues = $this->getCurrencyCodeAllowableValues();
        if (!in_array($currency_code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'currency_code', must be one of '%s'",
                    $currency_code,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets condition_list
     *
     * @return string[]
     */
    public function getConditionList()
    {
        return $this->container['condition_list'];
    }

    /**
     * Sets condition_list
     *
     * @param string[] $condition_list A list of conditions for the tax. Is empty if <code>chargeType</code> is not <code>conditional</code>.
     *
     * @return self
     */
    public function setConditionList($condition_list)
    {
        $allowedValues = $this->getConditionListAllowableValues();
        if (array_diff($condition_list, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'condition_list', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['condition_list'] = $condition_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


