<?php
/**
 * InlineResponse2003PropertyGuestInfoTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  com.lodgea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lodgea-php
 *
 * LODGEA SDK for php. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace com.lodgea\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2003PropertyGuestInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Information regarding requirements towards guests.
 * @package     com.lodgea
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2003PropertyGuestInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2003PropertyGuestInfo"
     */
    public function testInlineResponse2003PropertyGuestInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "guest_address_required"
     */
    public function testPropertyGuestAddressRequired()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "guest_contact_number_required"
     */
    public function testPropertyGuestContactNumberRequired()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "guest_name_list_required"
     */
    public function testPropertyGuestNameListRequired()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
