<?php
/**
 * PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriodTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com.lodgea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * lodgea-php
 *
 * LODGEA SDK for PHP. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace com.lodgea\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriodTest Class Doc Comment
 *
 * @category    Class
 * @description An object describing the cancellation grace periods.
 * @package     com.lodgea
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriodTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod"
     */
    public function testPropertiesPropertyIdGet200ResponsePropertyCancellationGracePeriod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hours_after_booking"
     */
    public function testPropertyHoursAfterBooking()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "weeks_before_check_in"
     */
    public function testPropertyWeeksBeforeCheckIn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
